ALTER TABLE USER
ADD PRIMARY KEY (id_user),
MODIFY COLUMN id_user INT UNSIGNED AUTO_INCREMENT,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL,
MODIFY COLUMN username VARCHAR(45) NOT NULL UNIQUE,
MODIFY COLUMN password VARCHAR(45) NOT NULL;

ALTER TABLE PERSONAGE
ADD PRIMARY KEY (id_personage),
MODIFY COLUMN id_personage INT UNSIGNED AUTO_INCREMENT,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL;

ALTER TABLE ADVENTURE
ADD PRIMARY KEY (id_adventure),
MODIFY COLUMN id_adventure INT UNSIGNED AUTO_INCREMENT,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL;

ALTER TABLE GAME
ADD PRIMARY KEY (id_game),
MODIFY COLUMN id_game INT UNSIGNED AUTO_INCREMENT,
MODIFY COLUMN id_user INT UNSIGNED,
MODIFY COLUMN id_personage INT UNSIGNED,
MODIFY COLUMN id_adventure INT UNSIGNED,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL,
ADD CONSTRAINT fk_user_game FOREIGN KEY (id_user) REFERENCES USER(id_user),
ADD CONSTRAINT fk_personage_game FOREIGN KEY (id_personage) REFERENCES PERSONAGE(id_personage),
ADD CONSTRAINT fk_adventure_game FOREIGN KEY (id_adventure) REFERENCES ADVENTURE(id_adventure);

ALTER TABLE STARRING
ADD PRIMARY KEY (id_adventure, id_personage),
MODIFY COLUMN id_personage INT UNSIGNED,
MODIFY COLUMN id_adventure INT UNSIGNED,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL,
ADD CONSTRAINT fk_personage_starring FOREIGN KEY (id_personage) REFERENCES PERSONAGE(id_personage),
ADD CONSTRAINT fk_adventure_starring FOREIGN KEY (id_adventure) REFERENCES ADVENTURE(id_adventure);

ALTER TABLE STEP
ADD PRIMARY KEY (id_step),
MODIFY COLUMN id_step INT UNSIGNED AUTO_INCREMENT,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL;

ALTER TABLE ANSWER
ADD PRIMARY KEY (id_answer),
MODIFY COLUMN id_answer INT UNSIGNED AUTO_INCREMENT,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL;

ALTER TABLE CHOICE
ADD PRIMARY KEY (id_choice),
MODIFY COLUMN id_choice INT UNSIGNED AUTO_INCREMENT,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL,
MODIFY COLUMN id_actual_step INT UNSIGNED,
MODIFY COLUMN id_next_step INT UNSIGNED,
MODIFY COLUMN id_previous_step INT UNSIGNED,
MODIFY COLUMN id_answer INT UNSIGNED,
ADD CONSTRAINT fk_actual_step_choice FOREIGN KEY (id_actual_step) REFERENCES STEP(id_step),
ADD CONSTRAINT fk_next_step_choice FOREIGN KEY (id_next_step) REFERENCES STEP(id_step),
ADD CONSTRAINT fk_previous_step_choice FOREIGN KEY (id_previous_step) REFERENCES STEP(id_step),
ADD CONSTRAINT fk_answer_choice FOREIGN KEY (id_answer) REFERENCES ANSWER(id_answer);

ALTER TABLE DECISIONMAKING 
ADD PRIMARY KEY (id_choice, id_step, id_game),
MODIFY COLUMN id_choice INT UNSIGNED,
MODIFY COLUMN id_step INT UNSIGNED,
MODIFY COLUMN id_game INT UNSIGNED,
MODIFY COLUMN modificationdate DATETIME NULL,
MODIFY COLUMN modificationuser VARCHAR(45) NULL,
ADD CONSTRAINT fk_choice_decisionmaking FOREIGN KEY (id_choice) REFERENCES CHOICE(id_choice),
ADD CONSTRAINT fk_step_decisionmaking FOREIGN KEY (id_step) REFERENCES STEP(id_step),
ADD CONSTRAINT fk_game_decisionmaking FOREIGN KEY (id_game) REFERENCES GAME(id_game);






